// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/media_notif.proto

package medianotif

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaNotifService_UploadFile_FullMethodName     = "/medianotif.MediaNotifService/UploadFile"
	MediaNotifService_SubscribeNotif_FullMethodName = "/medianotif.MediaNotifService/SubscribeNotif"
)

// MediaNotifServiceClient is the client API for MediaNotifService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaNotifServiceClient interface {
	// Client streaming
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error)
	// Server streaming
	SubscribeNotif(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
}

type mediaNotifServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaNotifServiceClient(cc grpc.ClientConnInterface) MediaNotifServiceClient {
	return &mediaNotifServiceClient{cc}
}

func (c *mediaNotifServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaNotifService_ServiceDesc.Streams[0], MediaNotifService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNotifService_UploadFileClient = grpc.ClientStreamingClient[FileChunk, UploadResponse]

func (c *mediaNotifServiceClient) SubscribeNotif(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaNotifService_ServiceDesc.Streams[1], MediaNotifService_SubscribeNotif_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNotifService_SubscribeNotifClient = grpc.ServerStreamingClient[Notification]

// MediaNotifServiceServer is the server API for MediaNotifService service.
// All implementations must embed UnimplementedMediaNotifServiceServer
// for forward compatibility.
type MediaNotifServiceServer interface {
	// Client streaming
	UploadFile(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error
	// Server streaming
	SubscribeNotif(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error
	mustEmbedUnimplementedMediaNotifServiceServer()
}

// UnimplementedMediaNotifServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaNotifServiceServer struct{}

func (UnimplementedMediaNotifServiceServer) UploadFile(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedMediaNotifServiceServer) SubscribeNotif(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error {
	return status.Error(codes.Unimplemented, "method SubscribeNotif not implemented")
}
func (UnimplementedMediaNotifServiceServer) mustEmbedUnimplementedMediaNotifServiceServer() {}
func (UnimplementedMediaNotifServiceServer) testEmbeddedByValue()                           {}

// UnsafeMediaNotifServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaNotifServiceServer will
// result in compilation errors.
type UnsafeMediaNotifServiceServer interface {
	mustEmbedUnimplementedMediaNotifServiceServer()
}

func RegisterMediaNotifServiceServer(s grpc.ServiceRegistrar, srv MediaNotifServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaNotifServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaNotifService_ServiceDesc, srv)
}

func _MediaNotifService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaNotifServiceServer).UploadFile(&grpc.GenericServerStream[FileChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNotifService_UploadFileServer = grpc.ClientStreamingServer[FileChunk, UploadResponse]

func _MediaNotifService_SubscribeNotif_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaNotifServiceServer).SubscribeNotif(m, &grpc.GenericServerStream[SubscribeRequest, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaNotifService_SubscribeNotifServer = grpc.ServerStreamingServer[Notification]

// MediaNotifService_ServiceDesc is the grpc.ServiceDesc for MediaNotifService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaNotifService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medianotif.MediaNotifService",
	HandlerType: (*MediaNotifServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _MediaNotifService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeNotif",
			Handler:       _MediaNotifService_SubscribeNotif_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/media_notif.proto",
}
